version: 2
jobs:
  build:
    working_directory: ~/saddlebags
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
      - store_test_results:
        path: test-reports/